service: lambda-cloudwatch-slack

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!./**'
    - './cloudwatch-slack/**'

custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
    invalidateCaches: true
    fileName: requirements.txt

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  lambdaHashingVersion: 20201221

functions:
  cloudwatch-slack:
    handler: cloudwatch-slack/lambda_function.lambda_handler
